package sqlkt

import com.squareup.kotlinpoet.ANY
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.MAP
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.STRING

/**
 * SQL text -> Kotlin source file.
 *
 * The generated file contains a single function
 *
 * ```
 * fun query(tables: Map<String, List<Map<String, Any?>>>): List<Map<String, Any?>>
 * ```
 *
 * plus a private runtime prelude, so it compiles against kotlin-stdlib alone.
 * `tables` maps table names (upper case) to rows; each row maps column names
 * (upper case) to values. The result rows use the query's output column names.
 */
class SqlToKotlinConverter(
    schema: SqlSchema,
    private val packageName: String = "generated",
    private val functionName: String = "query",
) {
    private val pipeline = CalcitePipeline(schema)

    private val rowType = MAP.parameterizedBy(STRING, ANY.copy(nullable = true))
    private val tablesType = MAP.parameterizedBy(STRING, LIST.parameterizedBy(rowType))
    private val resultType = LIST.parameterizedBy(rowType)

    fun convert(sql: String): String {
        val (rel, fieldNames) = pipeline.sqlToRel(sql)

        val relToKotlin = RelToKotlin(RexToKotlin(pipeline.rexBuilder))
        val (body, resultVar) = relToKotlin.generate(rel)

        val toMap = fieldNames.withIndex().joinToString(", ") { (i, _) -> "%S to row[$i]" }
        val function = FunSpec.builder(functionName)
            .addParameter("tables", tablesType)
            .returns(resultType)
            .addCode(body)
            .addStatement("return $resultVar.map { row -> mapOf($toMap) }", *fieldNames.toTypedArray())
            .build()

        val file = FileSpec.builder(packageName, "Query")
            .addFunction(function)
            .build()

        // The header is prepended and the runtime prelude appended as plain text
        // (KotlinPoet line-wraps file comments, which would corrupt the SQL).
        val header = buildString {
            appendLine("// Generated by sql-to-kotlin. Do not edit.")
            appendLine("// Source SQL:")
            sql.trim().lines().forEach { appendLine("//   $it") }
        }
        return header + file.toString() + RUNTIME_PRELUDE
    }
}
