package sqlkt

/**
 * SQL text -> Kotlin source file.
 *
 * The generated file contains a single function
 *
 * ```
 * fun query(tables: Map<String, List<Map<String, Any?>>>): List<Map<String, Any?>>
 * ```
 *
 * plus a private runtime prelude, so it compiles against kotlin-stdlib alone.
 * `tables` maps table names (upper case) to rows; each row maps column names
 * (upper case) to values. The result rows use the query's output column names.
 *
 * The source is assembled by hand (not with a codegen library): line breaks
 * and naming are chosen for human readability — named locals per column,
 * fluent operator chains, extracted common subexpressions.
 */
class SqlToKotlinConverter(
    schema: SqlSchema,
    private val packageName: String = "generated",
    private val functionName: String = "query",
) {
    private val pipeline = CalcitePipeline(schema)

    fun convert(sql: String): String {
        val (rel, fieldNames) = pipeline.sqlToRel(sql)

        val (rowClasses, body) =
            RelToKotlin(RexToKotlin(pipeline.rexBuilder)).generate(rel, fieldNames, functionName)

        return buildString {
            appendLine("// Generated by sql-to-kotlin. Do not edit.")
            appendLine("// Source SQL:")
            sql.trim().lines().forEach { appendLine("//   $it") }
            appendLine("package $packageName")
            appendLine()
            append(rowClasses)
            append(body)
            append(RUNTIME_PRELUDE)
        }
    }
}
